<button data-commandLinker-command="progressivis:cleanup_and_run" data-commandlinker-args='{"index": 1}' href="#" class='progressivis-cleanup-and-run-btn'>Run ProgressiVis</button>

In [1]:
from ipyprogressivis.widgets.chaining.constructor import Constructor
from ipyprogressivis.widgets.chaining.utils import create_root, get_header
from ipyprogressivis.widgets.chaining.custom import *
# ***************************************************************************************
# WARNING: This cell must only be executed using the 'Run ProgressiVis' button above.
# Do not execute it in any other way, as the result will not be as expected.
# For the same reason do not copy/paste the contents of this cell to execute it elsewhere
# ***************************************************************************************
header = get_header()
display(header.talker)
display(header.backup)
_ = header.constructor
with header.modules_out:
    display(header.board)
with header.widgets_out:
    display(header.manager)
header.talker.labcommand("notebook:hide-cell-code")
%reload_ext ipyprogressivis.magics
create_root(header.backup)

Talker()

BackupWidget()

In [2]:
# progressivis-snippets
import numpy as np
@register_function
@np.vectorize
def rain_level(val: float) -> str:
    if np.isnan(val) or val < 0.07:
        return "No"
    if val < 0.19:
        return "Light"
    return "Rain"

## root

In [3]:
# do not run this cell
display(header.constructor)
header.constructor.start_scheduler()
header.talker.labcommand('notebook:hide-cell-code')

Constructor(children=(IntProgress(value=0, description='Starting ProgressiVis ...', max=2, style=ProgressStyle…

Starting scheduler
# Scheduler added module(s): ['sink_1', 'variable_1']
# Scheduler added module(s): ['data_shape_1', 'sink_5']
# Scheduler deleted module(s): {'data_shape_1', 'sink_5'}
# Scheduler added module(s): ['data_shape_1', 'sink_6']
# Scheduler deleted module(s): {'sink_6', 'data_shape_1'}
# Scheduler added module(s): ['data_shape_1', 'sink_7']
# Scheduler deleted module(s): {'data_shape_1', 'sink_7'}
# Scheduler added module(s): ['data_shape_1', 'sink_8']
# Scheduler deleted module(s): {'data_shape_1', 'sink_8'}
# Scheduler added module(s): ['data_shape_1', 'sink_9']
# Scheduler deleted module(s): {'data_shape_1', 'sink_9'}

Exception in callback action on repeater_2
division by zero

## Weather

In [4]:
Constructor.widget('Weather', 0).run()

NodeCarrier(children=(HBox(children=(Button(button_style='danger', disabled=True, icon='trash', style=ButtonSt…

## Taxis

In [5]:
Constructor.widget('Taxis', 0).run()

NodeCarrier(children=(HBox(children=(Button(button_style='danger', disabled=True, icon='trash', style=ButtonSt…

## Join

In [6]:
Constructor.widget('Join', 0).run()

NodeCarrier(children=(HBox(children=(Button(button_style='danger', disabled=True, icon='trash', style=ButtonSt…

## Rich view

In [7]:
Constructor.widget('Rich view', 0).run()

NodeCarrier(children=(HBox(children=(Button(button_style='danger', disabled=True, icon='trash', style=ButtonSt…

## Group by

In [8]:
Constructor.widget('Group by', 0).run()

NodeCarrier(children=(HBox(children=(Button(button_style='danger', disabled=True, icon='trash', style=ButtonSt…

## Aggregate

In [9]:
Constructor.widget('Aggregate', 0).run()

NodeCarrier(children=(HBox(children=(Button(button_style='danger', disabled=True, icon='trash', style=ButtonSt…

## Norm

In [10]:
Constructor.widget('Norm', 0).run()

NodeCarrier(children=(HBox(children=(Button(button_style='danger', disabled=True, icon='trash', style=ButtonSt…

## Line chart

In [11]:
Constructor.widget('Line chart', 0).run()

NodeCarrier(children=(HBox(children=(Button(button_style='danger', disabled=True, icon='trash', style=ButtonSt…