<button data-commandLinker-command="progressivis:cleanup_and_run" data-commandlinker-args='{"index": 1}' href="#" class='progressivis-cleanup-and-run-btn'>Run ProgressiVis</button>

In [1]:
from ipyprogressivis.widgets.chaining.constructor import Constructor
from ipyprogressivis.widgets.chaining.utils import create_root, get_header
from ipyprogressivis.widgets.chaining.custom import *
# ***************************************************************************************
# WARNING: This cell must only be executed using the 'Run ProgressiVis' button above.
# Do not execute it in any other way, as the result will not be as expected.
# For the same reason do not copy/paste the contents of this cell to execute it elsewhere
# ***************************************************************************************
header = get_header()
display(header.talker)
display(header.backup)
_ = header.constructor
with header.modules_out:
    display(header.board)
with header.widgets_out:
    display(header.manager)
header.talker.labcommand("notebook:hide-cell-code")
%reload_ext ipyprogressivis.magics
create_root(header.backup)

Talker()

BackupWidget()

In [ ]:
# progressivis-snippets
@register_function
def mc_filter(df):
    pklon = df['pickup_longitude']
    pklat = df['pickup_latitude']
    dolon = df['dropoff_longitude']
    dolat = df['dropoff_latitude']
    return df[(pklon > -74.08) & (pklon < -73.5) &
              (pklat > 40.55) & (pklat < 41.00) &
              (dolon > -74.08) & (dolon < -73.5) &
              (dolat > 40.55) & (dolat < 41.00)]

## root

In [2]:
# do not run this cell
display(header.constructor)
header.constructor.start_scheduler()
header.talker.labcommand('notebook:hide-cell-code')

Constructor(children=(IntProgress(value=0, description='Starting ProgressiVis ...', max=2, style=ProgressStyle…

Starting scheduler
# Scheduler added module(s): ['sink_1', 'variable_1']

/home/poli/JDF2016/github/progressivis/progressivis/table/binning_index.py:282: RuntimeWarning: invalid value encountered in scalar floor_divide
  lower_bin = int((lower - origin) // bin_w)
/home/poli/JDF2016/github/progressivis/progressivis/table/binning_index.py:291: RuntimeWarning: invalid value encountered in scalar floor_divide
  upper_bin = int((upper - origin) // bin_w)
/home/poli/JDF2016/github/progressivis/progressivis/table/binning_index.py:394: RuntimeWarning: invalid value encountered in scalar floor_divide
  lower_bin = int((lower - origin) // bin_w)
/home/poli/JDF2016/github/progressivis/progressivis/table/binning_index.py:403: RuntimeWarning: invalid value encountered in scalar floor_divide
  upper_bin = int((upper - origin) // bin_w)
/home/poli/JDF2016/github/progressivis/progressivis/table/binning_index.py:394: RuntimeWarning: invalid value encountered in scalar floor_divide
  lower_bin = int((lower - origin) // bin_w)
/home/poli/JDF2016/github/progressivis/progressivis/table/binning_index.py:403: RuntimeWarning: invalid value encountered in scalar floor_divide
  upper_bin = int((upper - origin) // bin_w)
/home/poli/JDF2016/github/progressivis/progressivis/table/binning_index.py:394: RuntimeWarning: invalid value encountered in scalar floor_divide
  lower_bin = int((lower - origin) // bin_w)
/home/poli/JDF2016/github/progressivis/progressivis/table/binning_index.py:403: RuntimeWarning: invalid value encountered in scalar floor_divide
  upper_bin = int((upper - origin) // bin_w)
/home/poli/JDF2016/github/progressivis/progressivis/table/binning_index.py:394: RuntimeWarning: invalid value encountered in scalar floor_divide
  lower_bin = int((lower - origin) // bin_w)
/home/poli/JDF2016/github/progressivis/progressivis/table/binning_index.py:403: RuntimeWarning: invalid value encountered in scalar floor_divide
  upper_bin = int((upper - origin) // bin_w)
/home/poli/JDF2016/github/progressivis/progressivis/table/binning_index.py:394: RuntimeWarning: invalid value encountered in scalar floor_divide
  lower_bin = int((lower - origin) // bin_w)
/home/poli/JDF2016/github/progressivis/progressivis/table/binning_index.py:403: RuntimeWarning: invalid value encountered in scalar floor_divide
  upper_bin = int((upper - origin) // bin_w)
/home/poli/JDF2016/github/progressivis/progressivis/table/binning_index.py:394: RuntimeWarning: invalid value encountered in scalar floor_divide
  lower_bin = int((lower - origin) // bin_w)
/home/poli/JDF2016/github/progressivis/progressivis/table/binning_index.py:403: RuntimeWarning: invalid value encountered in scalar floor_divide
  upper_bin = int((upper - origin) // bin_w)
/home/poli/JDF2016/github/progressivis/progressivis/table/binning_index.py:394: RuntimeWarning: invalid value encountered in scalar floor_divide
  lower_bin = int((lower - origin) // bin_w)
/home/poli/JDF2016/github/progressivis/progressivis/table/binning_index.py:403: RuntimeWarning: invalid value encountered in scalar floor_divide
  upper_bin = int((upper - origin) // bin_w)
/home/poli/JDF2016/github/progressivis/progressivis/table/binning_index.py:394: RuntimeWarning: invalid value encountered in scalar floor_divide
  lower_bin = int((lower - origin) // bin_w)
/home/poli/JDF2016/github/progressivis/progressivis/table/binning_index.py:403: RuntimeWarning: invalid value encountered in scalar floor_divide
  upper_bin = int((upper - origin) // bin_w)

## Taxis

In [3]:
Constructor.widget('Taxis', 0)

NodeCarrier(children=(HBox(children=(Button(button_style='danger', icon='trash', style=ButtonStyle(), tooltip=…

## MCDensityMap

In [4]:
Constructor.widget('MCDensityMap', 0)

NodeCarrier(children=(HBox(children=(Button(button_style='danger', icon='trash', style=ButtonStyle(), tooltip=…